/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/script/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Your POST endpoint */
        post: operations["post-script-create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ScriptData */
        ScriptData: {
            speaker?: string;
            text?: string;
            caption?: string;
        };
        /** PostCreateScriptRequest */
        PostCreateScriptRequest: {
            prompt: string;
            previous_script?: components["schemas"]["PromptScriptData"][];
            reference?: string[];
            is_search?: boolean;
            speakers?: string[];
            word_count?: number;
        };
        /** PromptScriptData */
        PromptScriptData: {
            prompt: string;
            script?: components["schemas"]["ScriptData"][];
            reference?: string[];
        };
        /** PostCreateScriptResponse */
        PostCreateScriptResponse: {
            new_script: components["schemas"]["PromptScriptData"];
            previous_script?: components["schemas"]["PromptScriptData"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "post-script-create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PostCreateScriptRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostCreateScriptResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
